/security:
    post:
        security:
        - Bearer: []
        tags:
        - Security
        operationId: createSecurity
        description: Create a security.
        consumes:
        - application/json
        produces:
        - application/json
        parameters:
        - in: body
          name: json_data
          description: |
              Json Data of security to create
          schema:
              $ref: '#/definitions/SecurityInfo'
        responses:
            200:
                description: Created security successfully
                schema:
                    type: object
                    properties:
                        status:
                            type: string
                            example: success
                        data:
                            type: object
                            properties:
                                message:
                                    type: string
                                    example: Created security successfully
                                security:
                                    type: object
                                    properties:
                                        type:
                                            type: string
                                            enum: [warrant, preferred_stock, common_stock', option]
                                            example: preferred_stock
                                        name:
                                            type: string
                                            example: Security 1
                                        authorized:
                                            type: number
                                            example: 21
                                        liquidation:
                                            type: string
                                            example: liquidation 1
                                        accountId:
                                            type: string
                                            format: uuid
                                            example: 5172e1e8-7c0e-47ee-9fe1-082c619de99f
            400:
                description: Invalid input, object invalid

    put:
        security:
        - Bearer: []
        tags:
        - Security
        operationId: updateSecurity
        description: Update a security information.
        consumes:
        - application/json
        produces:
        - application/json
        parameters:
        - in: body
          name: json_data
          description: |
              Json Data of account to update
          schema:
              type: object
              required:
              - securityId
              properties:
                  securityId:
                      type: string
                      format: uuid
                      example: ddfa7024-812e-4f1f-92be-ab167010549b
                  type:
                      type: string
                      enum: [warrant, preferred_stock, common_stock', option]
                      example: preferred_stock
                  name:
                      type: string
                      example: Security 1
                  authorized:
                      type: number
                      example: 21
                  liquidation:
                      type: string
                      example: liquidation 1
                  accountId:
                      type: string
                      format: uuid
                      example: 5172e1e8-7c0e-47ee-9fe1-082c619de99f
        responses:
            200:
                description: Updated security successfully
                schema:
                    type: object
                    properties:
                        status:
                            type: string
                            example: success
                        data:
                            type: object
                            properties:
                                message:
                                    type: string
                                    example: Updated security successfully
                                uuid:
                                    type: string
                                    format: uuid
                                    example: ddfa7024-812e-4f1f-92be-ab167010549b
            400:
                description: Invalid input, object invalid

/security/{uuid}:
    get:
        security:
        - Bearer: []
        tags:
        - Security
        operationId: getSecurity
        description: |
            Get the security information
        produces:
        - application/json
        parameters:
        - in: path
          name: uuid
          type: string
          format: uuid
          required: true
          description: Pass search uuid for an unique security
        responses:
            200:
                description: Get security information successfully
                schema:
                    $ref: '#/definitions/SecurityInfo'
            400:
                description: Bad input parameter

    delete:
        security:
        - Bearer: []
        tags:
        - Security
        operationId: deleteSecurity
        description: |
            Delete the security information
        produces:
        - application/json
        parameters:
        - in: path
          name: uuid
          type: string
          format: uuid
          required: true
          description: Pass delete uuid for an unique security
        responses:
            200:
                description: Delete security information successfully
                schema:
                    type: object
                    properties:
                        status:
                            type: string
                            example: success
            400:
                description: Bad input parameter